# params/lanelet2_map_publisher.param.yaml
---

/**:
   ros__parameters:
   #   map_osm_file: "/opt/AutowareAuto/share/autoware_demos/data/autonomoustuff_parking_lot.osm"
   #   map_osm_file: "/home/nicolas/AutowareAuto/src/launch/autoware_demos/data/autonomoustuff_parking_lot_exported.osm"
     map_osm_file: "/home/nicolas/AutowareAuto/src/autoware-playground/panther_real_demo/data/pod_biurem_lanelet_map_FINAL.osm"
    #  map_osm_file: "/home/nicolas/AutowareAuto/src/autoware-playground/panther_real_demo/data/pod_biurem_lanelet_map_original.osm"


     # The earth-map transform is given by the point cloud map, but when the osm file is projected
     # into the map frame, they might not match exactly. These parameters allow specifying a small
     # correction to the position of the map frame origin for the purpose of this projection. 
     # Added as part of issue #847. The values are in degrees.
     origin_offset_lat: -5.239983224214484e-06
     origin_offset_lon: 4.5845488187978845e-06
