# config/pure_pursuit.param.yaml
---

/**:
  ros__parameters:
    tf_topic: "/tf"
    static_tf_topic: "/tf_static"
    timeout_ms:                  20
    controller:
      minimum_lookahead_distance:      2.0
      maximum_lookahead_distance:      100.0
      speed_to_lookahead_ratio:        0.1
      is_interpolate_lookahead_point:  true
      is_delay_compensation:           false
      emergency_stop_distance:         0.1
      speed_thres_traveling_direction: 6.0
      dist_front_rear_wheels:          0.44
