/**:
  ros__parameters:
    vehicle:
      cg_to_front_m: 0.23
      cg_to_rear_m: 0.23
      front_corner_stiffness: 0.1
      rear_corner_stiffness: 0.1
      mass_kg: 60.0
      yaw_inertia_kgm2: 1.0
      width_m: 0.7
      front_overhang_m: 0.15
      rear_overhang_m: 0.15
 